export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SET_POST_DATA = "SET_POST_DATA";
export const SET_COMMENT_DATA = "SET_COMMENT_DATA";
export const SET_CURRENT_POST = "SET_CURRENT_POST";

// ----Users states---- //

export const FETCH_U_REQUEST = "FETCH_U_REQUEST";
export const FETCH_U_SUCCESS = "FETCH_U_SUCCESS";

export const FETCH_REGISTRATION_ERROR = "FETCH_REGISTRATION_ERROR";
export const FETCH_AUTHORIZATION_ERROR = "FETCH_AUTHORIZATION_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";
